ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

ERROR:root:Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 52, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SVN\auto\TesseractPy3.py", line 58, in image_to_string
    text = retrieve_text(TEMP_RESULT_NAME)
  File "D:\SVN\auto\TesseractPy3.py", line 26, in retrieve_text
    inf = open(TEMP_RESULT_NAME + '.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt'

